# .github/workflows/python-testing-linux.yml
name: Linux Tests

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.rst'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.rst'

jobs:
  call-testing-linux:
    uses: casangi/toolviper/.github/workflows/python-testing-linux-template.yml@main
    with:
      cov_project: "graphviper"
      test-path: "tests/"
    secrets: inherit